### ISSUE TITLE
Error in ImageImport: changing the patient year 

### ISSUE THREAD

**Issue by ftadel** [IntrAnatSEEGSoftware/IntrAnat#2]
I just open ImageImport, go to the tab "Add patient", then try to change the year.
Every time I change the year, I get the error below. 

I guess this is the combination of two errors:
1) Some error with the patient management
2) A missing library libapt-pkg.so.4.12 in the error handling (current version is libapt-pkg.so.5.0)

What should I do for both issues?

```
Traceback (most recent call last):
  File "/home/ftadel/IntrAnat/IntrAnat/ImageImportWindow.py", line 1599, in updatePatientCode
    if self.prefs['projectSelected'][0] == 1 or self.prefs['projectSelected'][0] == 2:
IndexError: list index out of range
Error in sys.excepthook:
Traceback (most recent call last):
  File "/home/ftadel/IntrAnat/brainvisa-4.6.0/lib/python2.7/dist-packages/apport_python_hook.py", line 66, in apport_excepthook
    from apport.fileutils import likely_packaged, get_recent_crashes
  File "/home/ftadel/IntrAnat/brainvisa-4.6.0/lib/python2.7/dist-packages/apport/__init__.py", line 1, in <module>
    from apport.report import Report
  File "/home/ftadel/IntrAnat/brainvisa-4.6.0/lib/python2.7/dist-packages/apport/report.py", line 20, in <module>
    import apport.fileutils
  File "/home/ftadel/IntrAnat/brainvisa-4.6.0/lib/python2.7/dist-packages/apport/fileutils.py", line 22, in <module>
    from apport.packaging_impl import impl as packaging
  File "/home/ftadel/IntrAnat/brainvisa-4.6.0/lib/python2.7/dist-packages/apport/packaging_impl.py", line 20, in <module>
    import apt
  File "/home/ftadel/IntrAnat/brainvisa-4.6.0/lib/python2.7/dist-packages/apt/__init__.py", line 21, in <module>
    import apt_pkg
ImportError: libapt-pkg.so.4.12: cannot open shared object file: No such file or directory
```

**Comment by pdeman** [comment]
never had this...
i guess a ugly way to solve it would be to do a ln -s libapt-pkg.so.5.0 libapt-pkg.4.12

a less ugly way is to install libapt-pkg.4.12, older packages are always installable as well.

is there a project selected in the preference tab of image import ?
maybe for some reason the init didn't do its job

**Comment by ftadel** [comment]
> a less ugly way is to install libapt-pkg.4.12, older packages are always installable as well.

Ok, installing manually libapt-pkg4.12_1.0.9.8.4_amd64.deb. 
Is this something that should be reported to the BrainVISA developers?

> is there a project selected in the preference tab of image import ?

Yes. My protocol "subjects" created from running Morphologist in BrainVISA.
I just have this error left:

```
Traceback (most recent call last):
  File "/home/ftadel/IntrAnat/IntrAnat/ImageImportWindow.py", line 1599, in updatePatientCode
    if self.prefs['projectSelected'][0] == 1 or self.prefs['projectSelected'][0] == 2:
IndexError: list index out of range
```

**Comment by pdeman** [comment]
I can't reproduce this error.
my only guess is that self.prefs is not well loaded. try to modify the prefs tab, but specifying a project.
normally their should one selected by default.
otherwise select one and press save.
it should update the file at ~/.imageimport
maybe there is some write permission problem.

**Comment by pdeman** [comment]
I did a quick commit to better initialize self.prefs["projectSelected"]

**Comment by pdeman** [comment]
about "Ok, installing manually libapt-pkg4.12_1.0.9.8.4_amd64.deb.
Is this something that should be reported to the BrainVISA developers?"
yes it's more a brainvisa problem than an IntrAnat.

but it's even more a problem to report here I guess https://github.com/rickysarraf/apport (seems to come from there)

the strange thing is that I don't have this file and folder in my brainvisa 4.6 installation. neither in my 4.5.
I don't understand that ...

**Comment by ftadel** [comment]
Ok, will check with you new commit this afternoon. Thanks!

I reported the missing lib error here: 
http://brainvisa.info/forum/viewtopic.php?f=2&t=1836

**Comment by ftadel** [comment]
After your last commit:
```
Traceback (most recent call last):
  File "ImageImport.py", line 28, in <module>
    w = ImageImportWindow()
  File "/home/ftadel/IntrAnat/IntrAnat/ImageImportWindow.py", line 314, in __init__
    self.initialize()
  File "/home/ftadel/IntrAnat/IntrAnat/ImageImportWindow.py", line 615, in initialize
    projects[self.prefs['projectSelected'][0]].setChecked(True)
UnboundLocalError: local variable 'projects' referenced before assignment
```

**Comment by pdeman** [comment]
there a copy past problem. should be solved now (sorry I did the modification directly on my phone ...)

**Comment by ftadel** [comment]
Working!
Thanks
